apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: Chris-Testing-Company/backstage-testing
    backstage.io/techdocs-ref: dir:.
    jira/project-key: AWN
    jira/label: backstage-testing
  links:
    - url: https://infra.backstage.global-prod.rtkwlf.io
      title: Backstage (Production)
      icon: dashboard
    - url: https://infra.backstage.us002-dev.rtkwlf.io
      title: Backstage (Dev)
      icon: dashboard
    - url: https://clee.backstage.us001-dev.rtkwlf.io/
      title: Backstage (C LEE YO YO Test)
      icon: github
    - url: https://clee.backstage.us001-dev.rtkwlf.io/
      title: Backstage (C LEE YO YO Test 2)
      icon: github
    - url: https://github.com/rtkwlf/infrastructure/tree/main/cell/backstage
      title: Deployment IaC ABC
      icon: github
spec:
  lifecycle: production
  type: service
  owner: rnd_cd
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-testing-domains
  title: Backstage Testing Domains and Systems
  description: Domain and System entities for Backstage's component catalog
  annotations:
    github.com/project-slug: Chris-Testing-Company/backstage-testing
spec:
  type: url
  targets:
    - https://github.com/Chris-Testing-Company/backstage-testing/domains.yaml
