apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: Chris-Testing-Company/backstage-testing
    backstage.io/techdocs-ref: dir:.
    jira/project-key: AWN
    jira/label: backstage
spec:
  type: other
  lifecycle: unknown
  owner: site-reliability-engineering
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: rtkwlf-backstage-templates-testing
  title: Backstage Templates Testing
  description: Templates entities for testing
  annotations:
    github.com/project-slug: 'rtkwlf/backstage-entities'
spec:
  type: url
  targets:
    - https://github.com/Chris-Testing-Company/backstage-testing/blob/main/testing-template.yaml

