apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: Chris-Testing-Company/backstage-testing
    backstage.io/techdocs-ref: dir:.
    jira/project-key: AWN
    jira/label: backstage
spec:
  lifecycle: production
  type: service
  owner: rnd_cd